#!/usr/bin/env bash
cd "$(dirname "$0")/seeds"
i=0
w(){ printf '%s' "$1" > "seed_$i"; i=$((i+1)); }
w '\frac{1}{2}'
w '\sqrt[3]{x^2+y^2}'
w '\begin{array}{cc}a&b\\c&d\end{array}'
w '\begin{matrix}a&b\\c&d\end{matrix}'
w '\begin{pmatrix}1&2\\3&4\end{pmatrix}'
w '\multicolumn{2}{c}{x}'
w '\hdotsfor{3}'
w '\cellcolor{red}x'
w '\rowcolor{blue}'
w '\arrayrulecolor{green}'
w '\newcolumntype{L}{c}'
w '\newcommand{\x}{y}\x'
w '\newcommand{\x}[1]{#1#1}\x{a}'
w '\newenvironment{e}{\begin{array}{c}}{\end{array}}\begin{e}a\end{e}'
w '\def\x{y}\x'
w 'x^{2}_{3}'
w '\overline{\underline{x}}'
w '\hat{\tilde{\vec{x}}}'
w '\left(\frac{1}{2}\right)'
w '\left\{\begin{matrix}a\\b\end{matrix}\right\}'
w '\sideset{_1^2}{_3^4}\sum'
w '\overset{a}{b}'
w '\underset{a}{b}'
w '\stackrel{a}{b}'
w '\binom{n}{k}'
w '\sqrt[\frac{1}{2}]{x}'
w '\text{hello world}'
w '\mathbb{R}\mathcal{L}\mathfrak{g}'
w '\color{red}{x}'
w '\textcolor{blue}{y}'
w '\rule{2pt}{3pt}'
w '\hspace{2em}'
w '\raisebox{2pt}{x}'
w '\scalebox{2}{x}'
w '$$\int_0^\infty e^{-x}dx$$'
w '\[\sum_{i=1}^n i\]'
w '\begin{cases}a&x>0\\b&x<0\end{cases}'
w '\xrightarrow{abc}'
w '\substack{a\\b\\c}'
w '\prod\limits_{i}^{n}'
w '\accent{23}x'
w '\char"41'
w '\mathop{lim}\limits_x'
w '\frac\frac\frac1234'
w '\begin{tabular}{|c|c|}a&b\end{tabular}'
w '{\Huge x}{\tiny y}'
w '\phantom{xyz}\vphantom{a}\hphantom{b}'
w '\not\subset'
w '\boxed{x}'
w '\fbox{y}'
w '\colorbox{red}{z}'
